export default {
    black: "#000",
    blue: 'blue',
    danger: '#ff5252',
    darkGrey: '#0c0c0c',
    green: 'green',
    lightGrey: "#f8f4f4",
    mediumGrey: "#6e6969",
    primary: "#fc5c65",
    red: "red",
    secondary: "#4ecdc4",
    warmYellow: '#ffe66d',
    white: "#fff",
    yellow: 'yellow',
}